<div id="page">
    <header>
        <h2>{{ $titre }}</h2>
    </header>
    <main id="contenu">
        <article>
           {{ $table  }}
<!--            <table>-->
<!--                {% foreach ($donnees as $cle => $ligne) { %}-->
<!--                <tr><td>{{ $cle }}</td><td>{{ $ligne }}</td></tr>-->
<!--                {% } %}-->
<!--            </table>-->
        </article>
        <aside>Aside</aside>
    </main>
    <footer>
        <a href="page1">Page1</a>
    </footer>
</div>


