<nav id="menu">
    <h1><a id="titre" href="/">Bernard Thomas</a></h1>
    <div class="menu_encart">
        <h2><img src="images/potager.ico" height="30" width="30" /><span>Potager</span></h2>
        <a href="">Récoltes</a>
        <a href="">Cultures</a>
        <a href="">Synthèse2021 </a>
        <a href="">Synthèse2020 </a>
    </div>
    <div class="menu_encart">
        <h2><img src="images/tests.ico" height="30" width="30" /><span>Tests</span></h2>

        <a href="/index.php">Test affichage tableau</a>
        <a href="page1">Page1</a>
    </div>
</nav>



